### ISSUE TITLE
Library Compatibility with Thing Dev (ESP8266)

### ISSUE THREAD

**Issue by lizgreenwood** [sparkfun/MS5803-14BA_Breakout#2]
Observed on the Thing Dev. The ESP8266 has the same issue as https://github.com/sparkfun/MS5803-14BA_Breakout/issues/1

The same solution works as well. That is:

(1) Go to the .cpp file (here, Sparkfun_MS5803_I2C.cpp) and comment out Wire.begin() (here, in the MS5803::MS5803(ms5803_addr address) function)

(2) In the sketch, insert Wire.begin() after the Serial.begin() line. It won't work before it.

**Comment by bboyho** [comment]
Thanks @lizgreenwood ! I have updated this in v1.1.2 of the library => [ [https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library](https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library) ] . =)
