### ISSUE TITLE
Code compiles and uploads, but port becomes unavailable

### ISSUE THREAD

**Issue by ericsibored** [sparkfun/MS5803-14BA_Breakout#3]
I've been forced to use bootloader mode to reprogram my microcontrollers and regain access to the ports Arduino IDE (Feather M0, Razor IMU). 

When I try to upload the example code, it is successful but the port always disappears, removing the ability to check serial monitor or upload new code.

**Comment by bboyho** [comment]
Hi,

I'm sorry for the delay in reply. I was looking through our GitHub issues when I noticed this problem. Testing this out with the SAMD21 Mini, I had the same issue. I believe that this has something to do with how the &#42;.cpp initializes `Wire.begin()` in the code. Looking through the other issues in the product repo, I was able to get it working on the SAMD21 from the solutions presented in the other issues filed [https://github.com/sparkfun/MS5803-14BA_Breakout/issues/1](https://github.com/sparkfun/MS5803-14BA_Breakout/issues/1) and [https://github.com/sparkfun/MS5803-14BA_Breakout/issues/2](https://github.com/sparkfun/MS5803-14BA_Breakout/issues/2):

> (1) Go to the .cpp file (here, Sparkfun_MS5803_I2C.cpp) and comment out Wire.begin() (here, in the MS5803::MS5803(ms5803_addr address) function)
>
> (2) In the sketch, insert Wire.begin() after the Serial.begin() line. It won't work before it.

**Comment by bboyho** [comment]
I have updated this in v1.1.2 of the library => [ [https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library](https://github.com/sparkfun/SparkFun_MS5803-14BA_Breakout_Arduino_Library) ] . =)
